#pragma config(Sensor, S2,     colorSensor,    sensorColorNxtFULL)
#pragma config(Motor,  motorB,          MotorB,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          MotorC,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//%%%Algorithm%%%
//
//Start Task Main
//
//    Back up 6inches
//    Turn 90* right w.r.t. forward direction
//    while drive loop
//      drive toward yellow tape
//      stop at yellow tape
//    end while drive loop
//    write bigText message"YELLOW" in middle of display
//    wait1Msec(1000)
//end task main

task main()
{
	motor[motorB] = -10;
	motor[motorC] = -10;
	wait1Msec(2000);
	motor[motorB] = 10;
	motor[motorC] = 0;

	while(SensorValue[colorSensor] != 6)
	{
		motor[motorC] = 10;
	}
	displayBigTextLine(4, "YELLOW");
	wait1Msec(1000);
}
