#pragma config(Sensor, S1,     Roy,            sensorTouch)
#pragma config(Sensor, S4,     Sanderfer,      sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// HWK-5
//
// Individual Assignment
//
// By: Roy Sanderfer
// Date: 4/15/19
// Kit #: 56
// Class/Section #: ECE 1001-001
//
// Task Statement:
// Configure a Touch sensor on Input Port #1 (S1) on the front of the Bot
// and an Ultrasonic sensor on Input Port #4 (S2) in the rear of the Bot.
// Name the Touch sensor on port S1 your first name. Name the Ultrasonic
// sensor on port S4 your last name. Use the port alias names in your program.
//
// Place the Bot about 18 inches from one of the bullpen walls,
// pointing toward a bullpen wall. Use a for() loop and repeat 5 times.
// Call user function play sounds. Call user function forward. Call user
// function reverse.
//
// User function play sounds ? return void ? pass nothing to the function.
// Play 20 tones starting at 2 kHz and increasing 100 Hz each loop.
// Each tone will play for 100 msec. Use a for loop to play the tones.
//
//
// User function forward ? return void ? pass motor power to the function.
// Drive with synchronous motor control. Drive forward until the Touch
// sensor touches a wall, then stop, then play a sound file - you pick sound
// file. Wait 500 msec.
//
//
// User function reverse ? return void ? pass motor power to the function.
// Drive with synchronous motor control. Drive in reverse until the Ultrasonic
// sensor is < 15 cm, then stop, then play a different sound file - you pick sound
// file. Wait 250 msec.
//
//
// // #### Task Main Algorithm #### // //
//
// Call user function to playSound.
// Call user function to move forward.
// Call user function to go into reverse.
// Repeat 5 times using a for loop
//
// UserFunction playSounds Algorithm
// user function playSounds - returns void - nothing happens
// use a for loop
// user function plays 20 tones starting at 2 kHz and increasing 100 Hz each loop
// each tone will play for 100 mSec
//
// User Function forward Algorithm
// user function move forward - returns void - pass motor power to the function
// drive motors with synchronous motor control
// drive foward until the Touch sensor touches a wall
// stop
// play a sound file
// wait 500 mSec
//
// User Function reverse Algorithm
// user function reverse - return void - pass motore power to the function
// drive with synchronous motor control
// drive in reverse until ultrasonic sensor is < 15 cm
// stop
// play a different sound file
// wait 250 mSec
//
//User function prototype functions here
//
//
//
//
void  backward();

void	forward();

void	playTone();


task main()
{
	for(int loops = 0; loops<4; loops++)//for loop to run the program 5 times
	{
		playTone();
		forward();
		backward();
	}// End program for loop

	//***Main Void Code Algorithm***
	// call user function to play sound.
	// Call user function forward.
	// Call user function reverse.
	// Repeat 5 times using for loop


}// end main

void playTone()// start playTone user function
{
	int tone = 200;// initialize variable to 2 kHz


	for(tone = 2000; tone < 4000; tone+=100)//initializes sound at 2000Hz, with 20 increases of 100Hz reaching 3900Hz
	{
		playTone(tone,10);//play a 2Hz tone for 100 msecs
		while(bSoundActive)//while
		{sleep(1);}//wait for tone to play
	}//end for
} //end playTone User function



// UserFunction playsounds Algorithm
// user function play sounds - returns void - nothing happens
// use a for loop
// user function plays 20 tones starting at 2 kHz and increasing 100 Hz each loop
// each tone will play for 100 mSec

void forward()//begin user function forward
{
	if (SensorValue[Roy] == 0)// start if loop
	{
		nSyncedMotors = synchBC;
		nSyncedTurnRatio = 100;//sync motors B and C
		motor[motorB] = 30;// motors B and C drive forward at 30% power
	}// end if loop

	if (SensorValue[Roy] == 1)// start if loop
	{
		motor[motorB] = 0;
		playSoundFile("car_crash.rso");//play sound file
		sleep(1);
		wait1Msec(500);// wait 500 mSec
	}// end if
}// end forward user function

// User Function forwardAlgorithm
// user function drive forward - returns void - pass motor power to the function
// drive with synchronous motor control
// drive foward until the Touch sensor touches a wall
// stop
// play a sound file
// wait 500 mSec

void backward()// start backward user function
{
	int distance_in_cm = 15;
	while (SensorValue[Sanderfer] > distance_in_cm)// while loop
	{
		nSyncedMotors = synchBC;
		nSyncedTurnRatio = 100;//sync motors B and C
		motor[motorB] = -30;//reverse motors B and C at 40% power
	}// end while loop

	if (SensorValue[Sanderfer] <= distance_in_cm)// if loop
	{
		motor[motorB] = 0;//stop motor
		playSoundFile("danger.rso");// play sound file
		sleep(1);
		wait1Msec(250);//wait 250 Msec
  }

}// end backward user function

////User Function backward Algorithm
// user function reverse - return void - pass motor power to the function
// drive with synchronous motor control
// drive in reverse until ultrasonic sensor is < 15 cm
// stop
// play a different sound file
// wait 250 mSec
