#pragma config(Sensor, S2,     Roy,            sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
//
// HWK-4b
// Individual Assignment
//
// By: Roy Sanderfer
// Date: 3/7/19
// Kit#: 56
// Class/Section: ECE 1001-001
//
// Task Statement:
// Use the "Motors and Sensors Setup" drop down window under the
// Robot Tab to configure a Touch sensor on Input Port #2 (S2).
// Use your last name for the sensor alias.
//
// The program will loop 4 times using a for loop.
// Do the following in the loop:
//        Play a 3,500 Hz tone for 0.3 seconds.
//        Play a 2,800 Hz tone for 0.5 seconds.
//        Play a 4,000 Hz tone for o.7 seconds.
//        Play a 3,300 Hz tone for 0.1 seconds.
//
//        Then wait until the Touch sensor is pushed, then the
//        Bot will drive forward in synchronous mode fr 4 seconds.
//        Stop and play the sound file ("computer_hello.rso") 2 times
//        using a while loop.
//        Then the Bot will draw a square to the LCD.
//
//   Note: The starting corner of the square is at (column, row): (40,20)
//         with a length of 40 pixels per side.
//
//         Wait three seconds
//   end loop
//
//
// #####  Algorithm Program #4b  #####
//
// create #pragma touch sensor on S2 using my first name
//
// task main()
//
// place motors in synchronous mode
//
// playtone 3500Hz for 3 seconds
//  while sound loop
//    pause for 1 tick of 10Msecs
//  end sound loop
// playtone 2800Hz for 5 seconds
//  while sound loop
//    pause for 1 tick of 10Msecs
//  end sound loop
// playtone 4000Hz for 7 seconds
//  while sound loop
//    pause for 1 tick of 10Msecs
//  end sound loop
// playtone 3300Hz for 1 seconds
//  while sound loop
//    pause for 1 tick of 10Msecs
//  end sound loop
// create while loop for push button sensor
//    wait for 1Msec(1000) for 1 second pause
// end while loop
//
//   set motorB to 40
//   wait 1Msec(4000) for a 4 second pause
//   set motorB to 0
//
//  Play sound file computer_hello.rso
//  while sound loop
//    pause for 1 tick of 10Msecs
//  end sound loop
//
//  setpixel start point at (40,20)
//   wait1Msec(1000)
//  drawLine(40, 20, 40, 60)
//   wait1Msec(1000)
//  drawLine(40,60, 80, 60)
//   wait1Msec(1000)
//  drawLine(80,60, 80, 20)
//   wait1Msec(1000)
//  drawLine(80,20, 40, 20)
//   wait1Msec(1000)
//
// end program



task main()
{
	nSyncedMotors = synchBC; // motor B (mast) and Motor C (slave)

	playTone(3500,300); // play tone for 3 secs
	while(bSoundActive) // while loop for whle sound is playing
	{
		sleep(1); // pause for 1 Msec
	}
	playTone(2800,500); // play tone for 5 secs
	while(bSoundActive) // while loop for whle sound is playing
	{
		sleep(1); // pause for 1 Msec
	}
	playTone(4000,700); // play tone for 7 secs
	while(bSoundActive) // while loop for whle sound is playing
	{
		sleep(1); // pause for 1 Msec
	}
	playTone(3300,100); // play tone for 1 secs
	while(bSoundActive) // while loop for whle sound is playing
	{
		sleep(1); // pause for 1 Msec
	}


	while( SensorValue(Roy) == 0 )   // wait here until Touch sensor pushed
	{
   wait1Msec(2000); // wait 2 seconds
  }// end while loop

		motor[motorB] = 40; // set motor power B & C to 40%
    wait1Msec(4000); // wait for 4 seconds
		motor[motorB] = 0; // turn motors B & C off



	playSoundFile("computer_hello.rso"); // Play sound file computer_hello.rso
	while(bSoundActive)
	{
		sleep(1);
	} //end while sound loop


	setPixel(40,20); // set a pixel start point at 40,20
	wait1Msec(1000); //wait for 1 second
	drawLine(40, 20, 40, 60); // draw a 40 pixel line
	wait1Msec(1000);//wait for 1 second
	drawLine(40,60, 80, 60);// draw a 40 pixel line
	wait1Msec(1000);//wait for 1 second
	drawLine(80,60, 80, 20);// draw a 40 pixel line
	wait1Msec(1000);//wait for 1 second
	drawLine(80,20, 40, 20);// draw a 40 pixel line
	wait1Msec(1000);//wait for 1 second


}// end program
