#pragma config(Sensor, S2,     CrashPad,       sensorTouch)
#pragma config(Sensor, S3,     colorSensor,    sensorColorNxtFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
bool flag = false;
eraseDisplay();
displayCenteredTextLine(1, "Detected color:");
while (true)
{
flag = false;
if(SensorValue[colorSensor] == 1)
{
displayCenteredBigTextLine(4, "Black");
flag = true;
}
if(SensorValue[colorSensor] == 2)
{
displayCenteredBigTextLine(4, "Blue");
flag = true;
}
if(SensorValue[colorSensor] == 3)
{
displayCenteredBigTextLine(4, "Green");
flag = true;
}
if(SensorValue[colorSensor] == 4)
{
displayCenteredBigTextLine(4, "Yellow");
flag = true;
}
if(SensorValue[colorSensor] == 5)
{
displayCenteredBigTextLine(4, "Red");
flag = true;
}
if(SensorValue[colorSensor] == 6)
{
displayCenteredBigTextLine(4, "White");
flag = true;
}
if(flag == false)
{
displayCenteredBigTextLine(4, "Not a Color");
wait1Msec(400);
}
wait1Msec(100);  // wait 100 mSec
}  // end while true
}// end task main
