#pragma config(Sensor, S3,     Echo,           sensorSONAR)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//
//
//
//
//ultrasonic sensor
//user function
//float (range in cm) distance_in_cm
//
//
// By: Roy Sanderfer
// Date: 22 April 2019
// Class: ECE-1001-001
// Kit Number: 56
//
//Task 2: Program: Sound and Distance
//                 Design a program that calculates distances to objects in centimeters and
//                 plays a tone based on the distance measurement. Play a tone of 3,050Hz at
//                 0 cm and a 500Hz tone at 255 cm. Play the tones continuously ?no delays.
//
//
//
//          %%%%  Algorithm    %%%%%
// preprocessor directives
//
//
// start task main
//
//    define and init. variables
//     start while true loop
//       define float tone parameters
//       play tone
//     end while true loop
//end task main


task main()// start task main
{

		float tone = 0;// set float tone value
	    while(true)// start while true loop
	    {
		     tone = 3050 - (10 * SensorValue[Echo]);//set tone parameters
		     playTone(tone, 1);// play tone
	    }// end while true loop

}//end task main
