#pragma config(Sensor, S3,     Echo,           sensorSONAR)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
//
//ultrasonic sensor
//user function
//float (range in inches) distance_in_inches(float conversion constant)
//float (range in cm) distance_in_cm(float conversion constant)
//
//
// By: Roy Sanderfer
// Date: 22 April 2019
// Class: ECE-1001-001
// Kit Number: 56
//
//Task 1: Program: Measure Distance
//                 Design a program that calculates distances to objects in both centimeters and inches.
//                 The NXT must constantly show both measurements on the LCD display.
//                 One inch is equal to 2.54 cm. Display the measurement in inches as a float.
//                 When the sensor measures less than 8cm, play the sound file ?danger_x.rso? continuously.
//                 The program should run forever.Note ? The floor tiles in the Lab are 12 inches square.
//
//
//
//          %%%%  Algorithm    %%%%%
// preprocessor directives
//
// funtion prototype statement
//
// start task main
//
//    define and init. variables
//
//    start while driving loop
//      drive forward
//      call user function distance_in_inches
//      display inches text line
//      dislay cm text line
//       start if loop distance_inches
//        stop motors
//          play soundfile "danger_x.rso" continuously
//end task main


float distance_in_inches( float FUN_conversion );// float function

task main()// task main start
{
	nMotorEncoder[B] = 0; // set rotational motors to 0
	float conversion = 2.54;//  set float conversion
	float distance_inches = 0.0;// set distance_inches value
	float distance_cm = 0.0;// set distance_cm value

	while(SensorValue[Echo] <=255 )// start while loop
	{
		motor[motorB] = -30;// set motorB to -30%
		motor[motorC] = -30;// set motorC to -30%

		distance_inches = distance_in_inches(conversion);// define distance_inches
		distance_cm = SensorValue[Echo];// define distance_cm

		displayTextLine(0, "%d", distance_inches); // display distance_in_inches
		displayTextLine(4, "%d", distance_cm); // display distance_in_cm

		if(distance_inches <=3.15)// start if loop
		{
			motor[motorB] = 0;// set motor to 0%
			motor[motorC] = 0;// set motor to 0%

			playSoundFile("danger.rso");// play sound file
			while(bSoundActive)
			{
				sleep(1);
			}

	  }// end if loop

	}// end motor while loop

}// end task main

	float distance_in_inches( float FUN_conversion )// float user function
	{
		float temp = 0.0;// int temp

		temp = SensorValue[Echo] / FUN_conversion;// set int temp value

		return temp;// set return

	} // end user function - distance_in_inches
