#pragma config(Sensor, S1,     Touch,          sensorTouch)
#pragma config(Sensor, S3,     Echo,           sensorSONAR)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
//
//
//
//ultrasonic sensor
//
//
// By: Roy Sanderfer
// Date: 22 April 2019
// Class: ECE-1001-001
// Kit Number: 56
//
//Task 3: Program: Zig-Zag Escape
//                 Design a program that allows your NXT robot to never get stuck
//                 in an enclosed area ?three sided box.  It must utilize the Ultrasonic sensor in
//                 one direction and the Touch sensor in the otherdirection.
//                 The Bot must Zig-Zag out of the three-sided box. See the Figure below.
//                 The Bot can NOT touch a wall in the Ultrasonic sensor direction.  The Bot must
//                 touch the wall in the Touch sensor direction. When the Bot hits a wall
//                 (Touch sensor), the Bot should stop, play a sound file (you pick sound file)then continue the program.
//                 The Task is complete when both wheels arecompletely outside the open end of the box.
//                 The Bot must encounter the wall at least three times in both directions. Three times with Touch sensor and
//                 three times with the Ultrasonic sensor.
//
//
//
//          %%%%  Algorithm    %%%%%
// preprocessor directives
//
// start task main
//
//    define and init. variables
//
//    start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//    end while(SensorValue[Touch]==0)loop
//
//    start while(SensorValue[Echo]>=18)
//      set motors B and C to -30%
//    end while(SensorValue[Echo]>=18)
//
//    set motor C to 0% and set motor B to 30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//
//    start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//    end while(SensorValue[Touch]==0)loop
//
//    set motor C to 0% and set motor B to -30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//    start while(SensorValue[Echo]>=18)
//      set motors B and C to -30%
//    end while(SensorValue[Echo]>=18)
//
//    set motor C to 0% and set motor B to 30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//   start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//    end while(SensorValue[Touch]==0)loop
//
//    start while(SensorValue[Echo]>=18)
//      set motors B and C to -30%
//    end while(SensorValue[Echo]>=18)
//
//    set motor C to 0% and set motor B to 30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//   start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//    end while(SensorValue[Touch]==0)loop
//
//    set motor C to 0% and set motor B to -30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//    start while(SensorValue[Echo]>=18)
//      set motors B and C to -30%
//    end while(SensorValue[Echo]>=18)
//
//    set motor C to 0% and set motor B to 30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//   start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//    end while(SensorValue[Touch]==0)loop
//
//    start while(SensorValue[Echo]>=18)
//      set motors B and C to -30%
//    end while(SensorValue[Echo]>=18)
//
//    set motor C to 0% and set motor B to 30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//   start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//    end while(SensorValue[Touch]==0)loop
//
//    set motor C to 0% and set motor B to -30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//    start while(SensorValue[Echo]>=18)
//      set motors B and C to -30%
//    end while(SensorValue[Echo]>=18)
//
//    set motor C to 0% and set motor B to 30%
//    wait1Msec(400) for partial left hand turn
//    Set motor B to 0%
//
//   start while(SensorValue[Touch]==0)loop
//      set motors B and C to 30%
//   end while(SensorValue[Touch]==0)loop
//
//end task main





task main()// start task main
{
	nMotorEncoder[B] = 0;


	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }
  while(SensorValue[Echo]>=18)
  {
  	motor[motorB] = -30;
    motor[motorC] = -30;
	}
	motor[C]=0;
	motor[B]=30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }
  motor[C] =0;
  motor[B]=-30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Echo]>=18)
  {
  	motor[motorB] = -30;
		motor[motorC] = -30;
	}

	motor[C]=0;
	motor[B]=30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }

  while(SensorValue[Echo]>=18)
  {
  	motor[motorB] = -30;
		motor[motorC] = -30;
	}
	motor[C]=0;
	motor[B]=30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }
  motor[C] =0;
  motor[B]=-30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Echo]>=18)
  {
  	motor[motorB] = -30;
		motor[motorC] = -30;
	}

	motor[C]=0;
	motor[B]=30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }

  while(SensorValue[Echo]>=18)
  {
  	motor[motorB] = -30;
		motor[motorC] = -30;
	}
	motor[C]=0;
	motor[B]=30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }
  motor[C] =0;
  motor[B]=-30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Echo]>=18)
  {
  	motor[motorB] = -30;
		motor[motorC] = -30;
	}

	motor[C]=0;
	motor[B]=30;
	wait1Msec(400);
	motor[B]=0;

	while(SensorValue[Touch]==0)
	{
		motor[motorB] = 30;
		motor[motorC] = 30;

  }// end while loop

}// end task main
