#pragma config(Sensor, S1,     Button,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// loopTestProg.c
// by Roy Ssanderfer
// 2.20.19
// Kit #56
// Class ; ECE-1001-001
//
// Task Statement: Example program for a loop
//
//
//    ###  Algorithm   ####
//
// preprocessor directive
//
// task main
//   define & init. variables
//   loop 5 times - while loop
//     if (button pushed 77 flag == true)
//         LCD write value of loop
//         change flag = false
//     end if loop
//
//     if( Button not pushed  && flag == false)
//       flag = true
//       loop = loop + 1
//     end if
//
//    end loop 5 times
//
// end task main


task main()
{
	int loop = 0;

	bool flag = true;// boolean flag variable
	loop = 1;
	while( loop <= 5)
	{
		if( (SensorValue(Button) == 1) && ( flag == true)  )
		{
			displayTextLine(2, "Loop = %d", loop);
			flag = false;

		}// end if
		if( (SensorValue(Button) == 0 ) && ( flag == false ) )
		{
			flag = true;
			loop = loop + 1;
		}// end if loop


	} // end while loop


}
